version: '3'
services:
  hybrid:
    build:
      context: .
      dockerfile: Dockerfile
    image: biton-hybrid
    container_name: biton-hybrid-client
    ports:
    - "5000:5000"
    volumes:
    - .:/home/node/biton/
    - /home/node/node_modules/
    environment:
    - NODE_ENV=testing
    - HOST=0.0.0.0
    - NETMAGIC=test
    - DEBUG=biton*
